Limite use of the memory for Kibana

diff --git a/install/roles/auditorium/files/kibana b/install/roles/auditorium/files/kibana
--- a/install/roles/auditorium/files/kibana
+++ b/install/roles/auditorium/files/kibana
@@ -1,63 +1,24 @@
-#!/bin/bash
-# kibana daemon
-# description: kibana daemon
-# processname: kibana
+#!/bin/sh
+SCRIPT=$0
 
-DAEMON_PATH="/opt/kibana/bin/"
+# SCRIPT may be an arbitrarily deep series of symlinks. Loop until we have the concrete path.
+while [ -h "$SCRIPT" ] ; do
+  ls=$(ls -ld "$SCRIPT")
+  # Drop everything prior to ->
+  link=$(expr "$ls" : '.*-> \(.*\)$')
+  if expr "$link" : '/.*' > /dev/null; then
+    SCRIPT="$link"
+  else
+    SCRIPT=$(dirname "$SCRIPT")/"$link"
+  fi
+done
 
-DAEMON=./kibana
-DAEMONOPTS=""
+DIR="$(dirname "${SCRIPT}")/.."
+NODE="${DIR}/node/bin/node"
+test -x "$NODE" || NODE=$(which node)
+if [ ! -x "$NODE" ]; then
+  echo "unable to find usable node.js executable."
+  exit 1
+fi
 
-NAME=kibana
-DESC="My daemon description"
-PIDFILE=/var/run/$NAME.pid
-SCRIPTNAME=/etc/init.d/$NAME
-
-case "$1" in
-start)
-    printf "%-50s" "Starting $NAME..."
-    cd $DAEMON_PATH
-    PID=`$DAEMON $DAEMONOPTS > /dev/null 2>&1 & echo $!`
-    #echo "Saving PID" $PID " to " $PIDFILE
-    if [ -z $PID ]; then
-        printf "%s\n" "Fail"
-    else
-        echo $PID > $PIDFILE
-        printf "%s\n" "Ok"
-    fi
-;;
-status)
-    printf "%-50s" "Checking $NAME..."
-    if [ -f $PIDFILE ]; then
-    PID=`cat $PIDFILE`
-        if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
-            printf "%s\n" "Process dead but pidfile exists"
-        else
-            echo "Running"
-        fi
-    else
-        printf "%s\n" "Service not running"
-    fi
-;;
-stop)
-    printf "%-50s" "Stopping $NAME"
-    PID=`cat $PIDFILE`
-    cd $DAEMON_PATH
-    if [ -f $PIDFILE ]; then
-        kill -TERM $PID
-        printf "%s\n" "Ok"
-        rm -f $PIDFILE
-    else
-        printf "%s\n" "pidfile not found"
-    fi
-;;
-
-restart)
-    $0 stop
-    $0 start
-;;
-
-*)
-    echo "Usage: $0 {status|start|stop|restart}"
-    exit 1
-esac
+exec "${NODE}" --max-old-space-size=100  "${DIR}/src/cli" ${@}
